{
 "title": "Statistiche",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "fermo",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "simulazione",
     "rawSql": "SELECT tempo, mFermo FROM simulazione.statisticheSicure LIMIT 50 "
    },
    {
     "dataset": "simulazione",
     "rawSql": "SELECT tempo, mFermo FROM simulazione.statisticheRischiose LIMIT 50 "
    }
   ]
  },
  {
   "title": "nMacchine",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 9, "x": 13, "y": 0 },
   "targets": [
    {
     "dataset": "simulazione",
     "rawSql": "SELECT tempo, nMacchine FROM simulazione.statisticheSicure LIMIT 50 "
    },
    {
     "dataset": "simulazione",
     "rawSql": "SELECT tempo, nMacchine FROM simulazione.statisticheRischiose LIMIT 50 "
    }
   ]
  },
  {
   "title": "durata",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "simulazione",
     "rawSql": "SELECT tempo, mDurata FROM simulazione.statisticheSicure LIMIT 50 "
    },
    {
     "dataset": "simulazione",
     "rawSql": "SELECT tempo, mDurata FROM simulazione.statisticheRischiose LIMIT 50 "
    }
   ]
  },
  {
   "title": "incidenti",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "simulazione",
     "rawSql": "SELECT numeroIncidenti FROM simulazione.incidentiSicuri LIMIT 50 "
    },
    {
     "dataset": "simulazione",
     "rawSql": "SELECT numeroIncidenti FROM simulazione.incidentiRischiosi LIMIT 50 "
    }
   ]
  }
 ]
}